#! /usr/bin/env stack 
--stack --resolver lts-12.21 script --package ini --package directory --package text --package unordered-containers --package directory --package ansi-terminal

{-# LANGUAGE OverloadedStrings #-}

import System.Environment (getArgs, lookupEnv)
import Data.Ini
import Data.Text
import qualified Data.HashMap.Strict as H
import System.Directory
import qualified Data.List as L
import System.Console.ANSI
import Control.Exception

-- data AwsProfileIniComment = Initialized | CurrentProfile String

-- instance Show AwsProfileIniComment where
--     show Initialized = "generated by aws-profile"
--     show CurrentProfile str = show ("current profile: ", str)



-- parseComment :: String -> Maybe AwsProfileIniComment
-- parseComment str 
--     | str == "generated by aws-profile" = Just Initialized
--     | "current profile:" `elem` str     = Just CurrentProfile
--     | otherwise                        = Nothing


data Command = Init | Set | Show deriving Show
maybeSinkFilePath :: IO (Maybe FilePath)
maybeSinkFilePath = lookupEnv "AWS_CREDENTIALS"

maybeSourceFilePath :: IO (Maybe FilePath)
maybeSourceFilePath = lookupEnv "AWS_ALL_CREDENTIALS"

awsAccessKeyId :: Text
awsAccessKeyId = "aws_access_key_id"

awsSecretAccessKey :: Text
awsSecretAccessKey = "aws_secret_access_key"

envVarAndFileRequirements :: String
envVarAndFileRequirements = "You must set the following environment variables:\n" ++
                                        "AWS_CREDENTIALS=/Users/{username}/.aws/credentials\n" ++
                                        "AWS_ALL_CREDENTIALS={path/to/file/of/your/choice}\n\n" ++
                                        "WARNING! Be sure to put all your existing credentials in the AWS_ALL_CREDENTIALS file "++
                                        "before overwriting the standard one using this application!"
type Comment = String

currentProfileComment :: Text -> Comment
currentProfileComment profile = ";aws-profile: " ++ unpack profile ++ "\n\n"

type InvalidProfileError = String

invalidProfileErr :: [String] -> InvalidProfileError
invalidProfileErr validProfiles = "You must include a valid profile name. Your available AWS profiles are: " ++ show validProfiles

getEitherProfileArg :: [String] -> Ini -> IO (Either InvalidProfileError Text)
getEitherProfileArg args ini = do
    let validProfiles = L.filter (/= "default") (fmap unpack (sections ini))
    case args of
        [] -> return $ Left $ invalidProfileErr validProfiles
        x:_ -> if x `L.elem` validProfiles then return $ Right (pack x) else return $ Left $ invalidProfileErr validProfiles

catchExc :: IOException -> IO String
catchExc _ = return []

isInitialized :: FilePath -> IO Bool
isInitialized sourceFile = do
    file <- catch (readFile sourceFile) catchExc
    case file of 
        [] -> return False
        fileData -> if (L.head . L.lines) fileData == ";generated by aws-profile" then return True else return False

initAwsProfile :: IO ()
initAwsProfile =  do
    awsMasterCredsFile <- maybeSourceFilePath
    awsCredsFile       <- maybeSinkFilePath
    case (awsMasterCredsFile, awsCredsFile) of
        (Nothing, _) ->  print envVarAndFileRequirements
        (_, Nothing) ->  print envVarAndFileRequirements
        (Just sourceFile, Just sinkFile) -> do        
            errorOrIni <- readIniFile sinkFile
            case errorOrIni of
                Left err  -> putStrLn err
                Right ini -> do
                    writeFile sourceFile ";generated by aws-profile\n"
                    appendFile sourceFile $ unpack $ printIniWith (WriteIniSettings EqualsKeySeparator) ini
                    putStrLn "aws-profiles has been successfully initialized"
type Profile = String
parseComment :: String -> Either String Profile
parseComment comment = case L.words comment of
    [";aws-profile:", profile] -> Right profile
    _                        -> Left "You've not yet selected a profile using aws-profile."


showProfileName :: IO ()
showProfileName = do
    awsCredsFile       <- maybeSinkFilePath
    case awsCredsFile of
        Nothing -> putStrLn envVarAndFileRequirements
        Just fp -> do
            fileData <- catch (readFile fp) catchExc
            case fileData of
                [] -> putStrLn "You've not yet selected a profile using aws-profile."
                f -> case parseComment $ (L.head . L.lines) f of
                        Left err -> putStrLn err
                        Right profile -> putStrLn $ "You're current default profile is " ++ profile ++ "."




setProfile :: [String] -> IO ()
setProfile args =  do
    awsMasterCredsFile <- maybeSourceFilePath
    awsCredsFile       <- maybeSinkFilePath
    case (awsMasterCredsFile, awsCredsFile) of
        (Nothing, _) ->  print envVarAndFileRequirements
        (_, Nothing) ->  print envVarAndFileRequirements
        (Just sourceFile, Just sinkFile) -> do
            errorOrIni <- readIniFile sourceFile
            case errorOrIni of
                Left err  -> putStrLn err
                Right ini -> do
                    eitherProfileArg <- getEitherProfileArg args ini
                    case eitherProfileArg of
                        Left err -> putStrLn err
                        Right profile -> do
                            let accessKey = lookupValue profile awsAccessKeyId ini
                            let secret =  lookupValue profile awsSecretAccessKey ini
                            case (accessKey, secret) of
                                (Left err, _) -> print err
                                (_, Left err) -> print err
                                (Right a, Right s) -> do
                                    let newIni = Ini {unIni = H.insert "default" (H.fromList [(awsAccessKeyId, a), (awsSecretAccessKey, s)]) (unIni ini)}
                                    let settings = WriteIniSettings EqualsKeySeparator
                                    writeFile sinkFile $ currentProfileComment profile
                                    appendFile sinkFile $ unpack $ printIniWith settings newIni
                                    
                                    -- sets output text to green
                                    setSGR [SetColor Foreground Vivid Green]
                                    putStrLn $ "Your AWS profile is set to " ++ unpack profile


parseCommand :: String -> Either String Command          
parseCommand str = case str of
    "init" -> Right Init
    "set"  -> Right Set
    "show" -> Right Show
    _      -> Left str
    

main :: IO ()
main = do
    -- sets output text to red for errors    
    args <- getArgs
    case args of 
        []   -> do 
            putStrLn "You must specify a command. Supported commands are: init, set"
        x:xs -> do
            setSGR [SetColor Foreground Vivid Green]
            let cmd = parseCommand x
            case cmd of
                Right Init  -> initAwsProfile
                Right Set   -> setProfile xs
                Right Show  -> showProfileName
                Left str    -> putStrLn $ str ++ " is not a valid command. Supported comands are: init, set"


   