name:                aws-profile
version:             0.1.0.0
github:              "bradleywboggs/aws-profile"
license:             BSD3
author:              "Bradley Boggs"
maintainer:          "bradleywboggs@gmail.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/bradleywboggs/aws-profile#readme>

dependencies:
- base >= 4.7 && < 5
- ini
- directory
- text
- unordered-containers
- ansi-terminal 
- either


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  aws-profile:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
